### ISSUE TITLE
В классе Operation должно быть 2 поля с типом Account

### ISSUE THREAD

**Issue by stden** [levelp/SaveOurSalary#16]
## Expected vs Actual

Сейчас в классе Operation одно поле account с типом Account, и два текстовых поля для хранения информации о счетах.
Это может привести к дублированию и противоречиям в хранимой в БД информации. 
## Ожидается:
- В классе Operation должно быть 2 поля с типом Account (с которого перевод и на который перевод).
- Оба поля - ссылки на таблицу со счетами (Account),
- Если какого-то счёта нет, ссылка должна быть null,

**Comment by AglishP** [comment]
fix in 91003cea921074b05fd0bd96ba9267f9d9015441
