### ISSUE TITLE
Страница на которой показывается список пользователей зарегистированных на сайте

### ISSUE THREAD

**Issue by stden** [levelp/SaveOurSalary#21]
Список, в котором будут только логины. 
В дальнейшем можно будет сделать ссылки на профили пользователей.

**Comment by alexii-potapov** [comment]
Добавлено:
    persistence.xml  -  &quot;Production-MySQL&quot; ( отключено пересоздание базы)
    servlets/UserListServlet  - прописан  в web.xml
    ссылка в index.jsp 

```
sql/mysql.sql  создает  базу с таблицей user без колонки NAME
```
