### ISSUE TITLE
Перевод с дебетовой на кредитную с комиссией за перевод

### ISSUE THREAD

**Issue by stden** [levelp/SaveOurSalary#7]
- У пользователя 2 карты: дебетовая и кредитная
- Есть некоторая начальная сумма на дебетовой и на кредитной
- Пользователь переводит с дебетовой на кредитную
- При переводе снимается  комиссия:
  - Вариант 1: Фиксированная сумма
  - Вариант 2: Процент от суммы 
- В истории операции у обеих карт должна появится запись о переводе
- В операции должны быть ссылки на оба счёта

**Comment by AglishP** [comment]
0bcac847d97e2da85a45a941d1b2f1c69be13a3b этим коммитом закрыл задачу, но не совсем разобрался как слить все на github, сделать merge в master.
